---
# - name: Download Jenkins Repo
#   get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo validate_certs=no

# - name: Add Jenkins repository key
#   rpm_key: key=https://jenkins-ci.org/redhat/jenkins-ci.org.key state=present validate_certs=no

# - name: Install Jenkins
#   yum: name=jenkins state=present

# - name: Install Java
#   yum: name=java state=present

- name: Change Jenkins default port
  shell: java -jar jenkins.war --httpPort=8081

# - name: Check config Jenkins
#   command: chkconfig jenkins on

- name: Start Jenkins Service
  service: name=jenkins state=started